### ISSUE TITLE
Calling corestore.get with createIfMissing=false still creates the hypercore if it is missing

### ISSUE THREAD

**Issue by HDegroote** [holepunchto/corestore#28]
There appears to be a bug when passing the option 'createIfMissing' from hypercore to corestore. To reproduce:

```
const Corestore = require("corestore");
const ram = require('random-access-memory')

const corestore = new Corestore(ram)
const core = corestore.get({name: 'newcore', createIfMissing: false })

await core.ready() // Should throw due to createItMissing set to false, but doesn't

```
I've already identified the source of the issue. The opts get passed to the Hypercore constructor just fine, but the flow then becomes a bit complex. On this line in hypercore's constructor flow: https://github.com/hypercore-protocol/hypercore/blob/422209c6eab4ffcaa40d16bd7b5fda9ce82c33a5/index.js#L255, corestore's _preload() is called. This function creates a new Hypercore as well, and although it receives the original opts, it completely ignores the value of 'createIfMissing', setting it as:

(https://github.com/hypercore-protocol/corestore/blob/36bc46896cbea9db9f5b166cf2211b2ffd48324b/index.js#L181 )

The issue is fixed by doing something like
```
    let createIfMissing = !opts._discoveryKey
    if(opts.createIfMissing === false){ // Explicit override by user
      createIfMissing = false
    }

    const storageRoot = [CORES_DIR, id.slice(0, 2), id.slice(2, 4), id].join('/')
    const core = new Hypercore(p => this.storage(storageRoot + '/' + p), {
      _preready: this._preready.bind(this),
      autoClose: true,
      encryptionKey: opts.encryptionKey || null,
      userData,
      auth,
      cache: opts.cache,
      createIfMissing: createIfMissing,
      keyPair: keyPair && keyPair.publicKey
        ? {
            publicKey: keyPair.publicKey,
            secretKey: null
          }
        : null,
    })
```
 
If you confirm this is a good solution, I'm fine with making a PR with the change and a test.

A final note: all opts which are passed to corestore's `get` which are not explicitly handled in the preload method are ignored, as they are not passed on to the constructor call. I'm not sure they are all handled explicitly, and if they aren't, the ReadMe on `corestore.get` is a bit misleading (it states "All other options besides name and key will be forwarded to the Hypercore constructor.")

**Comment by mafintosh** [comment]
I'd just do

```
createIfMissing: opts.createIfMissing === false ? false : !opts._discoveryKey
```

but yes!
