### ISSUE TITLE
Add a master key option

### ISSUE THREAD

**Issue by andrewosh** [holepunchto/corestore#5]
Currently the master key is read from an internally-managed key file, but it'd be useful to let users pass in their own master keys.

**Comment by mjp0** [comment]
I think https://github.com/mafintosh/hyperdrive/issues/260 is related to this.

Any idea when this could be implemented? Without this you can't resurrect hyperdrive on another computer if the original computer breaks down because the private keys can't be exported.

**Comment by andrewosh** [comment]
Closing as outdated
