### ISSUE TITLE
random-access-storage compatibility

### ISSUE THREAD

**Issue by mjp0** [holepunchto/corestore#7]
I was trying to use hyperdrive with some more exotic random-access-storage options like random-access-network, and it seems that corestore has a problem with them. Is this something that can be fixed somehow or a new state of random-access-storage compatibility? 

Here's the error:
```
G:\Development\P2P\Experiments\hyperdrive\node_modules\hyperdrive\node_modules\corestore\index.js:99
    var core = hypercore(filename => this.storage(storageRoot + '/' + filename), key, {
                                          ^

TypeError: this.storage is not a function
```

**Comment by andrewosh** [comment]
@markopolojarvi mind showing me a code example of how you're passing in the random-access-storage instance? We definitely want this to be compatible with anything that matches the random-access-storage interface

**Comment by mjp0** [comment]
@andrewosh sure :)

```javascript
const { RAN, StreamTransport } = require("random-access-network");
const WebSocket = require("ws");
const WssTransport = require("./transport");
const sock = new WebSocket("ws://localhost:8088");
const hyperdrive = require("hyperdrive");

const transport = new WssTransport("test", sock);
const storage = RAN("test", transport);
sock.on("open", function() {
  const archive = hyperdrive(storage);
  archive.ready(() => {
    console.log('done')
  });
});
```

It's pretty much exactly the same as https://github.com/random-access-storage/random-access-network example.

**Comment by mafintosh** [comment]
should work fine in 6 if it's compatiable with RAS
