### ISSUE TITLE
Add documentation for `Corestore.close` method.

### ISSUE THREAD

**Issue by cowlicks** [holepunchto/corestore#72]
Hello, I needed a way to close a `Corestore` instance, but was not able to find it in the docs. I noticed the instance had a `close` method. Calling this worked for me. I think it should be documented.

I needed the `close` method for tests where I was closing and reopening instances that loaded from the same storage directory.

**Comment by mafintosh** [comment]
PR welcome

**Comment by arunkd13** [comment]
Looks quite old. Are there any other docs that need updating or can this be closed?
